---
title: "visualization"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
library(survival)
library(quantreg)
library(glmnet)
library(MASS)
library(pROC)
library(simsurv)
library(flexsurv)
library(tidyverse)
library(broom)
knitr::opts_chunk$set(echo = TRUE)
```

Visualization: survival probability vs. time 
```{r}
################# Generate Exp or Weib dist data ###################
cov <- data.frame(id = 1:500,
                    trt = rbinom(500, 1, 0.5))
  
# Simulate the event times

dat.weib0.5 <- simsurv(lambdas = 0.1, 
               gammas = 0.5, #change gamma,or use lognormal simulation
               betas = c(trt = -0.5), 
               x = cov)

dat.weib0.5 <- merge(cov, dat.weib0.5)


dat.exp <- simsurv(lambdas = 0.1, 
               gammas = 1, #change gamma,or use lognormal simulation
               betas = c(trt = -0.5), 
               x = cov)

dat.exp <- merge(cov, dat.exp)

dat.weib2 <- simsurv(lambdas = 0.1, 
               gammas = 2, #change gamma,or use lognormal simulation
               betas = c(trt = -0.5), 
               x = cov)

dat.weib2 <- merge(cov, dat.weib2)

dat.weib5 <- simsurv(lambdas = 0.1, 
               gammas = 5, #change gamma,or use lognormal simulation
               betas = c(trt = -0.5), 
               x = cov)

dat.weib5 <- merge(cov, dat.weib5)


################### Generate lognormal dist data ###################
# log-norm hazard fn
haz <- function(t, x, betas, mu, sigma) {
  exp(betas * (x)) * ((1/t*sigma)*dnorm(log(t)/sigma,mean=mu,sd=sigma))/
    (pnorm(-log(t)/sigma,mean=mu,sd=sigma))
}
# sim log-norm data
cov <- data.frame(trt = rbinom(100, 1, 0.5))
dat.lognorm <- cbind(simsurv(hazard = haz, 
                 x = cov,
                 mu = 0, 
                 sigma = 0.5,
                 betas = c(trt = -0.5)), 
                 cov)
  

################### Generate piece-wise dist data ###################
set.seed(1729)
ncuts <- 19
cuts <- sort(rexp(ncuts, rate = 0.1))
pw_times <- c(0, cuts)
N <- length(pw_times)
pw_haz <- sort(abs(rnorm(N)))
pw_haz <- abs(pw_haz - median(pw_haz))

haz <- function(t, x, betas, lb_interval, haz_interval, ...) {
  exp(betas * (x)) * haz_interval[findInterval(t, lb_interval)]
}

cov <- data.frame(trt = rbinom(100, 1, 0.5))
dat.piecewise <- cbind(simsurv(hazard = haz, 
                 x = cov,
                 lb_interval = pw_times, 
                 haz_interval = pw_haz, 
                 betas = c(trt = -0.5)), 
               cov)

# Merge the simulated event times onto covariate data frame
# No parameters need to be changed
s.weib0.5 <- with(dat.weib0.5,Surv(eventtime,status))
s.exp <- with(dat.exp,Surv(eventtime,status))
s.weib2 <- with(dat.weib2,Surv(eventtime,status))
s.weib5 <- with(dat.weib5,Surv(eventtime,status))
s.lognorm <- with(dat.lognorm,Surv(eventtime,status))
s.piecewise <- with(dat.piecewise,Surv(eventtime,status))

sExp1 <- survreg(s.weib0.5 ~ as.factor(trt),dist='exp',data=dat.weib0.5)
sExp2 <- survreg(s.exp ~ as.factor(trt),dist='exp',data=dat.exp)
sExp3 <- survreg(s.weib2 ~ as.factor(trt),dist='exp',data=dat.weib2)
sExp4 <- survreg(s.weib5 ~ as.factor(trt),dist='exp',data=dat.weib5)
sExp5 <- survreg(s.lognorm ~ as.factor(trt),dist='exp',data=dat.lognorm)
sExp6 <- survreg(s.piecewise ~ as.factor(trt),dist='exp',data=dat.piecewise)

sWei1 <- survreg(s.weib0.5 ~ as.factor(trt),dist='weibull',data=dat.weib0.5)
sWei2 <- survreg(s.exp ~ as.factor(trt),dist='weibull',data=dat.exp)
sWei3 <- survreg(s.weib2 ~ as.factor(trt),dist='weibull',data=dat.weib2)
sWei4 <- survreg(s.weib5 ~ as.factor(trt),dist='weibull',data=dat.weib5)
sWei5 <- survreg(s.lognorm ~ as.factor(trt),dist='weibull',data=dat.lognorm)
sWei6 <- survreg(s.piecewise ~ as.factor(trt),dist='weibull',data=dat.piecewise)

sCox1 <- coxph(s.weib0.5 ~ trt,data=dat.weib0.5)
sCox2 <- coxph(s.exp ~ trt,data=dat.exp)
sCox3 <- coxph(s.weib2 ~ trt,data=dat.weib2)
sCox4 <- coxph(s.weib5 ~ trt,data=dat.weib5)
sCox5 <- coxph(s.lognorm ~ trt,data=dat.lognorm)
sCox6 <- coxph(s.piecewise~ trt,data=dat.piecewise)

```

```{r,fig.align=center}

#fKM <- survfit(s ~ trt,data=dat) # fit the data using survfit() method in black line as reference.
#baseline <- basehaz(sCox)

par(mfrow=c(6,3),pty="m")

    plot(survfit(s.weib0.5 ~ trt,data=dat.weib0.5),main = 'Exponential')
    lines(predict(sExp1, newdata=list(trt=0),type="quantile",p=seq(.01,.99,by=.01)),seq(.99,.01,by=-.01),col="blue")
    lines(predict(sExp1, newdata=list(trt=1),type="quantile",p=seq(.01,.99,by=.01)),seq(.99,.01,by=-.01),col="blue")
    plot(survfit(s.weib0.5 ~ trt,data=dat.weib0.5),main = 'Weibull')
    lines(predict(sWei1, newdata=list(trt=0),type="quantile",p=seq(.01,.99,by=.01)),seq(.99,.01,by=-.01),col="red")
    lines(predict(sWei1, newdata=list(trt=1),type="quantile",p=seq(.01,.99,by=.01)),seq(.99,.01,by=-.01),col="red")
    plot(survfit(s.weib0.5 ~ trt,data=dat.weib0.5),main = 'Cox')
    lines(survfit(sCox1,newdata=data.frame(trt=1),conf.int = F),col='green')
    lines(survfit(sCox1,newdata=data.frame(trt=0),conf.int = F),col='green')
    
    plot(survfit(s.exp ~ trt,data=dat.exp))
    lines(predict(sExp2, newdata=list(trt=0),type="quantile",p=seq(.01,.99,by=.01)),seq(.99,.01,by=-.01),col="blue")
    lines(predict(sExp2, newdata=list(trt=1),type="quantile",p=seq(.01,.99,by=.01)),seq(.99,.01,by=-.01),col="blue")
    plot(survfit(s.exp ~ trt,data=dat.exp))
    lines(predict(sWei2, newdata=list(trt=0),type="quantile",p=seq(.01,.99,by=.01)),seq(.99,.01,by=-.01),col="red")
    lines(predict(sWei2, newdata=list(trt=1),type="quantile",p=seq(.01,.99,by=.01)),seq(.99,.01,by=-.01),col="red")
    plot(survfit(s.exp ~ trt,data=dat.exp))
    lines(survfit(sCox2,newdata=data.frame(trt=1),conf.int = F),col='green')
    lines(survfit(sCox2,newdata=data.frame(trt=0),conf.int = F),col='green')
    
    plot(survfit(s.weib2 ~ trt,data=dat.weib2))
    lines(predict(sExp3, newdata=list(trt=0),type="quantile",p=seq(.01,.99,by=.01)),seq(.99,.01,by=-.01),col="blue")
    lines(predict(sExp3, newdata=list(trt=1),type="quantile",p=seq(.01,.99,by=.01)),seq(.99,.01,by=-.01),col="blue")
    plot(survfit(s.weib2 ~ trt,data=dat.weib2))
    lines(predict(sWei3, newdata=list(trt=0),type="quantile",p=seq(.01,.99,by=.01)),seq(.99,.01,by=-.01),col="red")
    lines(predict(sWei3, newdata=list(trt=1),type="quantile",p=seq(.01,.99,by=.01)),seq(.99,.01,by=-.01),col="red")
    plot(survfit(s.weib2 ~ trt,data=dat.weib2))
    lines(survfit(sCox3,newdata=data.frame(trt=1),conf.int = F),col='green')
    lines(survfit(sCox3,newdata=data.frame(trt=0),conf.int = F),col='green')
   
    plot(survfit(s.weib5 ~ trt,data=dat.weib5))
    lines(predict(sExp4, newdata=list(trt=0),type="quantile",p=seq(.01,.99,by=.01)),seq(.99,.01,by=-.01),col="blue")
    lines(predict(sExp4, newdata=list(trt=1),type="quantile",p=seq(.01,.99,by=.01)),seq(.99,.01,by=-.01),col="blue")
    plot(survfit(s.weib5 ~ trt,data=dat.weib5))
    lines(predict(sWei4, newdata=list(trt=0),type="quantile",p=seq(.01,.99,by=.01)),seq(.99,.01,by=-.01),col="red")
    lines(predict(sWei4, newdata=list(trt=1),type="quantile",p=seq(.01,.99,by=.01)),seq(.99,.01,by=-.01),col="red")
    plot(survfit(s.weib5 ~ trt,data=dat.weib5))
    lines(survfit(sCox4,newdata=data.frame(trt=1),conf.int = F),col='green')
    lines(survfit(sCox4,newdata=data.frame(trt=0),conf.int = F),col='green')
    
    plot(survfit(s.lognorm ~ trt,data=dat.lognorm))
    lines(predict(sExp5, newdata=list(trt=0),type="quantile",p=seq(.01,.99,by=.01)),seq(.99,.01,by=-.01),col="blue")
    lines(predict(sExp5, newdata=list(trt=1),type="quantile",p=seq(.01,.99,by=.01)),seq(.99,.01,by=-.01),col="blue")
    plot(survfit(s.lognorm ~ trt,data=dat.lognorm))
    lines(predict(sWei5, newdata=list(trt=0),type="quantile",p=seq(.01,.99,by=.01)),seq(.99,.01,by=-.01),col="red")
    lines(predict(sWei5, newdata=list(trt=1),type="quantile",p=seq(.01,.99,by=.01)),seq(.99,.01,by=-.01),col="red")
    plot(survfit(s.lognorm ~ trt,data=dat.lognorm))
    lines(survfit(sCox5,newdata=data.frame(trt=1),conf.int = F),col='green')
    lines(survfit(sCox5,newdata=data.frame(trt=0),conf.int = F),col='green')
    
    plot(survfit(s.piecewise ~ trt,data=dat.piecewise))
    lines(predict(sExp6, newdata=list(trt=0),type="quantile",p=seq(.01,.99,by=.01)),seq(.99,.01,by=-.01),col="blue")
    lines(predict(sExp6, newdata=list(trt=1),type="quantile",p=seq(.01,.99,by=.01)),seq(.99,.01,by=-.01),col="blue")
    plot(survfit(s.piecewise ~ trt,data=dat.piecewise))
    lines(predict(sWei6, newdata=list(trt=0),type="quantile",p=seq(.01,.99,by=.01)),seq(.99,.01,by=-.01),col="red")
    lines(predict(sWei6, newdata=list(trt=1),type="quantile",p=seq(.01,.99,by=.01)),seq(.99,.01,by=-.01),col="red")
    plot(survfit(s.piecewise ~ trt,data=dat.piecewise))
    lines(survfit(sCox6,newdata=data.frame(trt=1),conf.int = F),col='green')
    lines(survfit(sCox6,newdata=data.frame(trt=0),conf.int = F),col='green')
```



```{r,include=FALSE,echo=FALSE,eval=FALSE}
#plot hazards: 

set.seed(1729)
ncuts <- 19
cuts <- sort(rexp(ncuts, rate = 0.1))
pw_times <- c(0, cuts)
N <- length(pw_times)
pw_haz <- sort(abs(rnorm(N)))
pw_haz <- abs(pw_haz - median(pw_haz))

haz_piece <- function(t, ...) {
   pw_haz[findInterval(t, pw_times)]
}

haz_log <- function(t) {
  ((1/t*0.5)*dnorm(log(t)/0.5,mean=-0,sd=0.5))/
    (pnorm(-log(t)/0.5,mean=0,sd=0.5))
}

haz_weibull_0.5 = function(t){
  0.5 * t^(0.5-1)
}




p <- ggplot(data = data.frame(x = 0), mapping = aes(x = x))

p + 
  stat_function(fun = haz_piece, aes(color = "piece-wise")) + 
  stat_function(fun = haz_log, aes(col = "log-normal")) + 
  stat_function(fun = haz_weibull_0.5, aes(col = "weibull (gamma = 0.5)")) + 
  stat_function(fun = haz_exponential, aes(col = "pink")) + 
  xlim(0,20) + 
  ylim(0,2) + 
  theme_bw() + 
  scale_color_manual(name = "Hazard Functions", 
                     values = c("red", "green", "blue", "orange"), 
                     labels = c("log-normal", "piece-wise", "exponential", "weibull (gamma = 0.5)" )) + 
  theme(legend.position="bottom") + 
  labs(x = "t", y = "hazard")
  
```

