---
title: "Simulation"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(survival)
library(quantreg)
library(glmnet)
library(MASS)
library(pROC)
library(simsurv)
library(flexsurv)
library(tidyverse)
library(broom)
```

```{r}

sim_weibull = function(gamma, n){
  
  #sim weibull data
  cov <- data.frame(id = 1:n,
                    trt = rbinom(n, 1, 0.5))
  dat <- simsurv(lambdas = 0.1, 
               gammas = gamma, 
               betas = c(trt = -0.5), 
               x = cov, 
               maxt = 5)
  dat <- merge(cov, dat)
  
  #fit models
  fit.exponential <- tidy(survreg(Surv(dat$eventtime, dat$status) ~ dat$trt, dist = "exponential"))
  fit.weibull <- tidy(survreg(Surv(dat$eventtime, dat$status) ~ dat$trt, dist = "weibull"))
  fit.cox <- tidy(coxph(Surv(dat$eventtime, dat$status) ~ dat$trt))
  
  #extract beta
  result = tibble(exp_beta = c(-fit.exponential$estimate[1]), 
                  weibull_beta = c(-fit.weibull$estimate[1]),
                  cox_beta =c(fit.cox$estimate), 
                  dist = "weibull",
                  gamma = gamma, 
                  n = n)
  return(result)
}



# run sim 1000 times, with n = 100

#RESULTS
set.seed(11)

#gamma=0.5
results0 = map_dfr(.x = c(rep(0.5, 1000)), 
        ~sim_weibull(gamma = .x, n = 100))

write.csv(results0,"results_gamma0.5.csv")

#gamma=1 (exponential)
results1 = map_dfr(.x = c(rep(1, 1000)), 
        ~sim_weibull(gamma = .x, n = 100))

write.csv(results1,"results_gamma1.csv")

#gamma=2
results2 = map_dfr(.x = c(rep(2, 1000)), 
        ~sim_weibull(gamma = .x, n = 100))

write.csv(results2,"results_gamma2.csv")

#gamma=5
results3 = map_dfr(.x = c(rep(5, 1000)), 
        ~sim_weibull(gamma = .x, n = 100))

write.csv(results3,"results_gamma5.csv")
```



```{r}
#log-norm hazard fn
haz <- function(t, x, betas, mu, sigma) {
  exp(betas * (x)) * ((1/t*sigma)*dnorm(log(t)/sigma,mean=mu,sd=sigma))/
    (pnorm(-log(t)/sigma,mean=mu,sd=sigma))
}



sim_lnorm = function(n){
  
  #sim log-norm data
  cov <- data.frame(trt = rbinom(n, 1, 0.5))
  dat <- cbind(simsurv(hazard = haz, 
                 x = cov,
                 mu = 0, 
                 sigma = 0.5,
                 betas = c(trt = -0.5)), 
               cov)
  
  #fit models
  fit.exponential <-tidy(survreg(Surv(dat$eventtime, dat$status) ~ dat$trt, dist = "exponential"))
  fit.weibull <- tidy(survreg(Surv(dat$eventtime, dat$status) ~ dat$trt, dist = "weibull"))
  fit.cox <- tidy(coxph(Surv(dat$eventtime, dat$status) ~ dat$trt))
  
  #extract beta
  result = tibble(exp_beta = c(-fit.exponential$estimate[1]), 
                  weibull_beta = c(-fit.weibull$estimate[1]),
                  cox_beta =c(fit.cox$estimate), 
                  dist = "lnorm",
                  gamma = NA, 
                  n = n)
}

# run sim 1000 times, n = 100
set.seed(11)

#lognormal results
results4 = map_dfr(.x = c(rep(100, 1000)), 
        ~sim_lnorm(n = .x))

write.csv(results4,"results_lognormal.csv")
```

```{r}
#piece-wise hazard sim

set.seed(1729)
ncuts <- 19
cuts <- sort(rexp(ncuts, rate = 0.1))
pw_times <- c(0, cuts)
N <- length(pw_times)
pw_haz <- sort(abs(rnorm(N)))
pw_haz <- abs(pw_haz - median(pw_haz))

haz <- function(t, x, betas, lb_interval, haz_interval, ...) {
  exp(betas * (x)) * haz_interval[findInterval(t, lb_interval)]
}

sim_piece = function(n){
  
  cov <- data.frame(trt = rbinom(n, 1, 0.5))


  dat <- cbind(simsurv(hazard = haz, 
                 x = cov,
                 lb_interval = pw_times, 
                 haz_interval = pw_haz, 
                 betas = c(trt = -0.5)), 
               cov)

  
  #fit models
  fit.exponential <-tidy(survreg(Surv(dat$eventtime, dat$status) ~ dat$trt, dist = "exponential"))
  fit.weibull <- tidy(survreg(Surv(dat$eventtime, dat$status) ~ dat$trt, dist = "weibull"))
  fit.cox <- tidy(coxph(Surv(dat$eventtime, dat$status) ~ dat$trt))
  
  #extract beta
  result = tibble(exp_beta = c(-fit.exponential$estimate[1]), 
                  weibull_beta = c(-fit.weibull$estimate[1]),
                  cox_beta =c(fit.cox$estimate), 
                  dist = "piecewise",
                  gamma = NA, 
                  n = n)
}


#piecewise results
set.seed(11)

results5 = map_dfr(.x = c(rep(100, 1000)), 
        ~sim_piece(n = .x))

write.csv(results5,"results_piecewise.csv")

```



Fit and plot weibull dist using three models
```{r}
#PLOTTING HAZARDS

#Exponential (gamma=1), hazard=1/beta=lambda

plot_weibull = function(gamma, n){
cov <- data.frame(id = 1:n,
                    trt = rbinom(500, 1, 0.5))
  
# Simulate the event times
dat <- simsurv(lambdas = 0.1, 
               gammas = gamma, 
               betas = c(trt = -0.5), 
               x = cov)
dat <- merge(cov, dat)
s <- with(dat,Surv(eventtime,status))
sWei <- survreg(s ~ as.factor(trt),dist='weibull',data=dat)
sExp <- survreg(s ~ as.factor(trt),dist='exp',data=dat)
sCox <- coxph(s ~ trt,data=dat)

s <- with(dat,Surv(eventtime,status))
fKM <- survfit(s ~ trt,data=dat) # fit the data using survfit() method in black line as reference.
baseline <- basehaz(sCox) # use Cox model to plot hazard rates
par(mfrow=c(2,2))
    plot(fKM,main = 'cox')
    lines(survfit(sCox,newdata=data.frame(trt=1),conf.int = F),col='blue')
    lines(survfit(sCox,newdata=data.frame(trt=0),conf.int = F),col='red')
    plot(fKM,main = 'weibull')
    lines(predict(sWei, newdata=list(trt=0),type="quantile",p=seq(.01,.99,by=.01)),seq(.99,.01,by=-.01),col="red")
    lines(predict(sWei, newdata=list(trt=1),type="quantile",p=seq(.01,.99,by=.01)),seq(.99,.01,by=-.01),col="blue")
    plot(fKM,main = 'exponential')
    lines(predict(sExp, newdata=list(trt=0),type="quantile",p=seq(.01,.99,by=.01)),seq(.99,.01,by=-.01),col="red")
    lines(predict(sExp, newdata=list(trt=1),type="quantile",p=seq(.01,.99,by=.01)),seq(.99,.01,by=-.01),col="blue")
    plot(baseline$time, baseline$hazard, type='l',main="Hazard rates??", xlab = "Time", ylab = "Hazard") 
    lines(baseline$time, exp(sCox$coefficients[1])*baseline$hazard, col="blue")
}

plot_weibull(0.5, 1000)

```

Fit and plot lognormal dist using three models
```{r}
plot_lnorm = function(n){
  
# sim log-norm data
cov <- data.frame(trt = rbinom(n, 1, 0.5))
dat <- cbind(simsurv(hazard = haz, 
                 x = cov,
                 mu = 0, 
                 sigma = 0.5,
                 betas = c(trt = -0.5)), 
               cov)
  
# Merge the simulated event times onto covariate data frame
# No parameters need to be changed
s <- with(dat,Surv(eventtime,status))
sWei <- survreg(s ~ as.factor(trt),dist='weibull',data=dat)
sExp <- survreg(s ~ as.factor(trt),dist='exp',data=dat)
sCox <- coxph(s ~ trt,data=dat)

s <- with(dat,Surv(eventtime,status))
fKM <- survfit(s ~ trt,data=dat) # fit the data using survfit() method in black line as reference.
baseline <- basehaz(sCox) # use Cox model to plot hazard rates
par(mfrow=c(2,2))
    plot(fKM,main = 'cox')
    lines(survfit(sCox,newdata=data.frame(trt=1),conf.int = F),col='blue')
    lines(survfit(sCox,newdata=data.frame(trt=0),conf.int = F),col='red')
    plot(fKM,main = 'weibull')
    lines(predict(sWei, newdata=list(trt=0),type="quantile",p=seq(.01,.99,by=.01)),seq(.99,.01,by=-.01),col="red")
    lines(predict(sWei, newdata=list(trt=1),type="quantile",p=seq(.01,.99,by=.01)),seq(.99,.01,by=-.01),col="blue")
    plot(fKM,main = 'exponential')
    lines(predict(sExp, newdata=list(trt=0),type="quantile",p=seq(.01,.99,by=.01)),seq(.99,.01,by=-.01),col="red")
    lines(predict(sExp, newdata=list(trt=1),type="quantile",p=seq(.01,.99,by=.01)),seq(.99,.01,by=-.01),col="blue")
    plot(baseline$time, baseline$hazard, type='l',main="Hazard rates??", xlab = "Time", ylab = "Hazard") 
    lines(baseline$time, exp(sCox$coefficients[1])*baseline$hazard, col="blue")
}

plot_lnorm(100)
```

